export const kenyaLocationSuggestions = [
  "Mombasa County",
  "Mvita, Mombasa County",
  "Likoni, Mombasa County",
  "Nyali, Mombasa County",
  "Kwale County",
  "Ukunda, Kwale County",
  "Diani, Kwale County",
  "Lungalunga, Kwale County",
  "Kilifi County",
  "Kilifi Town, Kilifi County",
  "Malindi, Kilifi County",
  "Mariakani, Kilifi County",
  "Tana River County",
  "Hola, Tana River County",
  "Garsen, Tana River County",
  "Bura, Tana River County",
  "Lamu County",
  "Lamu Town, Lamu County",
  "Mpeketoni, Lamu County",
  "Witu, Lamu County",
  "Taita Taveta County",
  "Voi, Taita Taveta County",
  "Taveta, Taita Taveta County",
  "Wundanyi, Taita Taveta County",
  "Garissa County",
  "Garissa Town, Garissa County",
  "Ijara, Garissa County",
  "Dadaab, Garissa County",
  "Wajir County",
  "Wajir Town, Wajir County",
  "Habaswein, Wajir County",
  "Eldas, Wajir County",
  "Mandera County",
  "Mandera Town, Mandera County",
  "El Wak, Mandera County",
  "Rhamu, Mandera County",
  "Marsabit County",
  "Marsabit Town, Marsabit County",
  "Moyale, Marsabit County",
  "Loiyangalani, Marsabit County",
  "Isiolo County",
  "Isiolo Town, Isiolo County",
  "Merti, Isiolo County",
  "Garbatulla, Isiolo County",
  "Meru County",
  "Meru Town, Meru County",
  "Maua, Meru County",
  "Mikinduri, Meru County",
  "Tharaka-Nithi County",
  "Chuka, Tharaka-Nithi County",
  "Marimanti, Tharaka-Nithi County",
  "Kathwana, Tharaka-Nithi County",
  "Embu County",
  "Embu Town, Embu County",
  "Runyenjes, Embu County",
  "Mbeere, Embu County",
  "Kitui County",
  "Kitui Town, Kitui County",
  "Mwingi, Kitui County",
  "Mutomo, Kitui County",
  "Machakos County",
  "Machakos Town, Machakos County",
  "Athi River, Machakos County",
  "Kangundo, Machakos County",
  "Makueni County",
  "Wote, Makueni County",
  "Mbooni, Makueni County",
  "Makindu, Makueni County",
  "Nyandarua County",
  "Ol Kalou, Nyandarua County",
  "Engineer, Nyandarua County",
  "Njabini, Nyandarua County",
  "Nyeri County",
  "Nyeri Town, Nyeri County",
  "Karatina, Nyeri County",
  "Othaya, Nyeri County",
  "Kirinyaga County",
  "Kerugoya, Kirinyaga County",
  "Sagana, Kirinyaga County",
  "Mwea, Kirinyaga County",
  "Murang'a County",
  "Murang'a Town, Murang'a County",
  "Kandara, Murang'a County",
  "Kenol, Murang'a County",
  "Kiambu County",
  "Thika, Kiambu County",
  "Ruiru, Kiambu County",
  "Kiambu Town, Kiambu County",
  "Turkana County",
  "Lodwar, Turkana County",
  "Kakuma, Turkana County",
  "Lokichoggio, Turkana County",
  "West Pokot County",
  "Kapenguria, West Pokot County",
  "Chepareria, West Pokot County",
  "Sigor, West Pokot County",
  "Samburu County",
  "Maralal, Samburu County",
  "Baragoi, Samburu County",
  "Wamba, Samburu County",
  "Trans Nzoia County",
  "Kitale, Trans Nzoia County",
  "Kiminini, Trans Nzoia County",
  "Endebess, Trans Nzoia County",
  "Uasin Gishu County",
  "Eldoret, Uasin Gishu County",
  "Burnt Forest, Uasin Gishu County",
  "Turbo, Uasin Gishu County",
  "Elgeyo-Marakwet County",
  "Iten, Elgeyo-Marakwet County",
  "Kapsowar, Elgeyo-Marakwet County",
  "Chepkorio, Elgeyo-Marakwet County",
  "Nandi County",
  "Kapsabet, Nandi County",
  "Nandi Hills, Nandi County",
  "Mosoriot, Nandi County",
  "Baringo County",
  "Kabarnet, Baringo County",
  "Mogotio, Baringo County",
  "Marigat, Baringo County",
  "Laikipia County",
  "Nanyuki, Laikipia County",
  "Nyahururu, Laikipia County",
  "Rumuruti, Laikipia County",
  "Nakuru County",
  "Nakuru Town, Nakuru County",
  "Njoro, Nakuru County",
  "Naivasha, Nakuru County",
  "Molo, Nakuru County",
  "Gilgil, Nakuru County",
  "Narok County",
  "Narok Town, Narok County",
  "Kilgoris, Narok County",
  "Suswa, Narok County",
  "Kajiado County",
  "Kajiado Town, Kajiado County",
  "Kitengela, Kajiado County",
  "Ngong, Kajiado County",
  "Kericho County",
  "Kericho Town, Kericho County",
  "Litein, Kericho County",
  "Ainamoi, Kericho County",
  "Bomet County",
  "Bomet Town, Bomet County",
  "Sotik, Bomet County",
  "Longisa, Bomet County",
  "Kakamega County",
  "Kakamega Town, Kakamega County",
  "Mumias, Kakamega County",
  "Malava, Kakamega County",
  "Vihiga County",
  "Mbale, Vihiga County",
  "Luanda, Vihiga County",
  "Chavakali, Vihiga County",
  "Bungoma County",
  "Bungoma Town, Bungoma County",
  "Webuye, Bungoma County",
  "Kimilili, Bungoma County",
  "Busia County",
  "Busia Town, Busia County",
  "Malaba, Busia County",
  "Funyula, Busia County",
  "Siaya County",
  "Siaya Town, Siaya County",
  "Bondo, Siaya County",
  "Ugunja, Siaya County",
  "Kisumu County",
  "Kisumu City, Kisumu County",
  "Ahero, Kisumu County",
  "Muhoroni, Kisumu County",
  "Homa Bay County",
  "Homa Bay Town, Homa Bay County",
  "Mbita, Homa Bay County",
  "Oyugis, Homa Bay County",
  "Migori County",
  "Migori Town, Migori County",
  "Kehancha, Migori County",
  "Rongo, Migori County",
  "Kisii County",
  "Kisii Town, Kisii County",
  "Ogembo, Kisii County",
  "Suneka, Kisii County",
  "Nyamira County",
  "Nyamira Town, Nyamira County",
  "Keroka, Nyamira County",
  "Nyansiongo, Nyamira County",
  "Nairobi County",
  "Westlands, Nairobi County",
  "Embakasi, Nairobi County",
  "Karen, Nairobi County",
  "Kasarani, Nairobi County",
] as const;

export const kenyaLocationListId = "kenya-location-suggestions";
